Repository hh99-delivery-project/main_repo, pull requests merged in 2024-03, with the labels that each got.

#1 feat: html layout
  src/main/resources/static/img/logo.png
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/include-link.html
  src/main/resources/templates/common/include-script.html
  src/main/resources/templates/index2.html
Labels: enhancement

#2 기본 패키지 및 메서드 구성
  build.gradle
  src/main/java/com/example/delivery/config/PasswordConfig.java
  src/main/java/com/example/delivery/config/SwaggerConfig.java
  src/main/java/com/example/delivery/constant/Role.java
  src/main/java/com/example/delivery/controller/TestController.java
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/java/com/example/delivery/domain/User.java
  src/main/java/com/example/delivery/dto/UserLoginDto.java
  src/main/java/com/example/delivery/dto/UserRegisterDto.java
  src/main/java/com/example/delivery/exception/CustomException.java
  src/main/java/com/example/delivery/exception/ErrorCode.java
  src/main/java/com/example/delivery/exception/ErrorResponse.java
  src/main/java/com/example/delivery/jwt/JwtUtil.java
  src/main/java/com/example/delivery/repository/UserRepository.java
  src/main/java/com/example/delivery/security/JwtAuthenticationFilter.java
  src/main/java/com/example/delivery/security/JwtAuthorizationFilter.java
  src/main/java/com/example/delivery/security/UserDetailsImpl.java
  src/main/java/com/example/delivery/security/UserDetailsServiceImpl.java
  src/main/java/com/example/delivery/service/user/UserService.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
  src/main/resources/properties.yml
Labels: enhancement

#3 Feature/order create
  src/main/java/com/example/delivery/controller/OrderController.java
  src/main/java/com/example/delivery/domain/Order.java
  src/main/java/com/example/delivery/dto/OrderDto.java
  src/main/java/com/example/delivery/dto/OrderMenuDto.java
  src/main/java/com/example/delivery/repository/OrderRepository.java
  src/main/java/com/example/delivery/service/user/OrderService.java
  src/main/java/com/example/delivery/service/user/OrderServiceImpl.java
  src/main/resources/templates/home.html
  src/main/resources/templates/index2.html
Labels: enhancement

#4 Feature/order create
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/java/com/example/delivery/controller/api/ValidationController.java
  src/main/java/com/example/delivery/dto/UserRegisterDto.java
  src/main/java/com/example/delivery/service/user/UserService.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
  src/main/resources/properties.yml
  src/main/resources/templates/common/include-script.html
  src/main/resources/templates/index.html
  src/main/resources/templates/register.html
Labels: enhancement

#5 feat: 사장님 페이지 html 작성
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/domain/Order.java
  src/main/resources/templates/common/header.html
  src/main/resources/templates/store/menu/menu-list.html
  src/main/resources/templates/store/menu/menu-register.html
  src/main/resources/templates/store/mypage.html
  src/main/resources/templates/store/order/order-list.html
  src/main/resources/templates/store/store-register.html
Labels: enhancement

#6 이메일 로직 구현
  build.gradle
  src/main/java/com/example/delivery/config/WebSecurityConfig.java
  src/main/java/com/example/delivery/controller/EmailVerificationController.java
  src/main/java/com/example/delivery/repository/UserRepository.java
  src/main/java/com/example/delivery/service/email/EmailVerificationService.java
  src/main/java/com/example/delivery/service/order/OrderService.java
  src/main/java/com/example/delivery/service/order/OrderServiceImpl.java
  src/main/java/com/example/delivery/service/user/OrderService.java
  src/main/java/com/example/delivery/service/user/OrderServiceImpl.java
  src/main/java/com/example/delivery/tool/email/EmailProperties.java
  src/main/java/com/example/delivery/tool/email/EmailTool.java
  src/main/java/com/example/delivery/tool/redis/RedisConfig.java
  src/main/java/com/example/delivery/tool/redis/RedisTool.java
Labels: enhancement

#7 이메일 인증 회원가입 구현 완료
  src/main/java/com/example/delivery/controller/EmailVerificationController.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
  src/main/resources/templates/register.html
Labels: enhancement

#8 회원가입 기능완료
  src/main/java/com/example/delivery/domain/User.java
  src/main/java/com/example/delivery/dto/UserRegisterDto.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
  src/main/resources/templates/register.html
Labels: enhancement

#9 로그인 구현 완료(security)
  src/main/java/com/example/delivery/DeliveryApplication.java
  src/main/java/com/example/delivery/config/WebSecurityConfig.java
  src/main/java/com/example/delivery/controller/HomeController.java
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/java/com/example/delivery/jwt/JwtUtil.java
  src/main/java/com/example/delivery/security/JwtAuthenticationFilter.java
  src/main/java/com/example/delivery/security/JwtAuthorizationFilter.java
  src/main/resources/static/css/style.css
  src/main/resources/static/img/logo.png
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
Labels: enhancement

#11 like 서비스 Controller 작성 전까지 완료
  src/main/java/com/example/delivery/controller/LikeController.java
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/domain/Like.java
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/dto/LikeDto.java
  src/main/java/com/example/delivery/exception/ErrorCode.java
  src/main/java/com/example/delivery/repository/LikeRepository.java
  src/main/java/com/example/delivery/service/Like/LikeService.java
  src/main/java/com/example/delivery/service/Like/LikeServiceImpl.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/main/java/com/example/delivery/service/user/UserService.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
Labels: enhancement

#12 feat: 사장님 음식점 메뉴 등록 및 메뉴 리스트 구현
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/domain/Menu.java
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/dto/StoreDto.java
  src/main/java/com/example/delivery/repository/MenuRepository.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/main/resources/templates/store/menu/menu-list.html
  src/main/resources/templates/store/menu/menu-register.html
Labels: enhancement

#13 Feature/order detail
  src/main/java/com/example/delivery/DeliveryApplication.java
  src/main/java/com/example/delivery/controller/OrderController.java
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/controller/api/MenuController.java
  src/main/java/com/example/delivery/domain/Order.java
  src/main/java/com/example/delivery/domain/OrderMenu.java
  src/main/java/com/example/delivery/domain/Timestamped.java
  src/main/java/com/example/delivery/dto/MenuDto.java
  src/main/java/com/example/delivery/dto/OrderDto.java
  src/main/java/com/example/delivery/dto/OrderMenuDto.java
  src/main/java/com/example/delivery/dto/UserDto.java
  src/main/java/com/example/delivery/repository/OrderMenuRepostiory.java
  src/main/java/com/example/delivery/repository/OrderRepository.java
  src/main/java/com/example/delivery/service/menu/MenuService.java
  src/main/java/com/example/delivery/service/menu/MenuServiceImpl.java
  src/main/java/com/example/delivery/service/order/OrderService.java
  src/main/java/com/example/delivery/service/order/OrderServiceImpl.java
  src/main/java/com/example/delivery/service/ordermenu/OrderMenuService.java
  src/main/java/com/example/delivery/service/ordermenu/OrderMenuServiceImpl.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/main/java/com/example/delivery/service/user/UserService.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
  src/main/resources/static/img/logo.png
  src/main/resources/static/img/logo2.png
  src/main/resources/templates/common/include-script.html
  src/main/resources/templates/store/order/order-detail.html
  src/main/resources/templates/store/order/order-list.html
  src/main/resources/templates/store/order/order-success.html
  src/main/resources/templates/store/store-main.html
Labels: enhancement

#14 fix: order detail
  src/main/java/com/example/delivery/controller/api/MenuController.java
  src/main/resources/templates/home.html
  src/main/resources/templates/store/store-main.html
Labels: bug

#15 feat : kakao 로그인 구현 및 로컬로그인 오류 수정
  src/main/java/com/example/delivery/config/RestTemplateConfig.java
  src/main/java/com/example/delivery/config/WebSecurityConfig.java
  src/main/java/com/example/delivery/controller/HomeController.java
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/java/com/example/delivery/domain/User.java
  src/main/java/com/example/delivery/dto/KakaoUserInfoDto.java
  src/main/java/com/example/delivery/jwt/JwtUtil.java
  src/main/java/com/example/delivery/repository/UserRepository.java
  src/main/java/com/example/delivery/security/JwtAuthenticationFilter.java
  src/main/java/com/example/delivery/security/JwtAuthorizationFilter.java
  src/main/java/com/example/delivery/security/UserDetailsServiceImpl.java
  src/main/java/com/example/delivery/service/KakaoService.java
  src/main/resources/static/js/basic.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/store/mypage.html
Labels: bug, enhancement

#18 Feature/order complete
  src/main/java/com/example/delivery/controller/OrderController.java
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/repository/StoreRepository.java
  src/main/java/com/example/delivery/service/order/OrderServiceImpl.java
  src/main/resources/templates/store/order/order-list.html
Labels: enhancement

#19 fix: 주문 완료 처리 시, 사장님 계정 포인트에 금액 추가
  src/main/java/com/example/delivery/domain/User.java
  src/main/java/com/example/delivery/service/order/OrderServiceImpl.java
Labels: bug, enhancement

#20 카테고리 기반 반환처리
  src/main/java/com/example/delivery/controller/LikeController.java
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/domain/Like.java
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/dto/LikeDto.java
  src/main/java/com/example/delivery/dto/StoreDto.java
  src/main/java/com/example/delivery/repository/LikeRepository.java
  src/main/java/com/example/delivery/repository/StoreRepository.java
  src/main/java/com/example/delivery/service/Like/LikeService.java
  src/main/java/com/example/delivery/service/Like/LikeServiceImpl.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
Labels: help wanted

#21 fix: 주문 결제 관련 버그 수정
  src/main/java/com/example/delivery/controller/OrderController.java
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/domain/User.java
  src/main/java/com/example/delivery/dto/StoreDto.java
  src/main/java/com/example/delivery/service/order/OrderService.java
  src/main/java/com/example/delivery/service/order/OrderServiceImpl.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/main/resources/templates/common/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/search-store.html
  src/main/resources/templates/store/order/order-fail.html
  src/main/resources/templates/store/order/order-success.html
  src/main/resources/templates/store/store-main.html
Labels: bug

#23 feat: CEO 권한만 음식점 등록/수정 관련 페이지 접근 가능
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/resources/templates/store/mypage.html
  src/main/resources/templates/user-mypage.html
Labels: enhancement

#24 feat: user mypage 회원 정보 페이지 구현
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/java/com/example/delivery/service/user/UserService.java
  src/main/java/com/example/delivery/service/user/UserServiceImpl.java
  src/main/resources/templates/user-mypage.html
Labels: enhancement

#25 feat: keyword search 기능 구현
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/repository/MenuRepository.java
  src/main/java/com/example/delivery/repository/StoreRepository.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/main/resources/templates/home.html
  src/main/resources/templates/search-store.html
Labels: enhancement

#26 Feature/paging
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/dto/StorePageDto.java
  src/main/java/com/example/delivery/repository/StoreRepository.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/main/resources/templates/home.html
  src/main/resources/templates/search-store.html
Labels: enhancement

#27 query dsl
  build.gradle
  src/main/generated/com/example/delivery/domain/QMenu.java
  src/main/generated/com/example/delivery/domain/QOrder.java
  src/main/generated/com/example/delivery/domain/QOrderMenu.java
  src/main/generated/com/example/delivery/domain/QStore.java
  src/main/generated/com/example/delivery/domain/QTimestamped.java
  src/main/generated/com/example/delivery/domain/QUser.java
  src/main/java/com/example/delivery/controller/LikeController.java
  src/main/java/com/example/delivery/domain/Like.java
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/repository/LikeRepository.java
  src/main/java/com/example/delivery/repository/StoreRepository.java
  src/main/java/com/example/delivery/repository/dslrepository/StoreRepositoryCustom.java
  src/main/java/com/example/delivery/repository/dslrepository/StoreRepositoryCustomImpl.java
  src/main/java/com/example/delivery/service/Like/LikeService.java
  src/main/java/com/example/delivery/service/Like/LikeServiceImpl.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/test/java/com/example/delivery/DeliveryApplicationTests.java
Labels: enhancement

#29 Feature/https
  src/main/java/com/example/delivery/DeliveryApplication.java
  src/main/java/com/example/delivery/controller/StoreController.java
  src/main/java/com/example/delivery/controller/UserController.java
  src/main/java/com/example/delivery/service/KakaoService.java
  src/main/resources/bootsecurity.p12
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/search-store.html
  src/main/resources/templates/store/menu/menu-list.html
  src/main/resources/templates/store/store-main.html
Labels: enhancement

#30 feat : DSL 테스트 및 성능테스트
  src/main/java/com/example/delivery/domain/Store.java
  src/main/java/com/example/delivery/dto/StoreDto.java
  src/main/java/com/example/delivery/dto/StorePageDto.java
  src/main/java/com/example/delivery/dto/StoreProDto.java
  src/main/java/com/example/delivery/repository/StoreRepository.java
  src/main/java/com/example/delivery/repository/dslrepository/StoreRepositoryCustom.java
  src/main/java/com/example/delivery/repository/dslrepository/StoreRepositoryCustomImpl.java
  src/main/java/com/example/delivery/service/store/StoreService.java
  src/main/java/com/example/delivery/service/store/StoreServiceImpl.java
  src/test/java/com/example/delivery/DeliveryApplicationTests.java
  src/test/java/com/example/delivery/service/store/StoreServiceImplTest.java
  src/test/java/com/example/delivery/service/store/StoreServiceImplTest2.java
Labels: enhancement

#32 fix: https ssl
  src/main/java/com/example/delivery/service/KakaoService.java
  src/main/resources/bootsecurity.p12
  src/main/resources/keystore.p12
  src/main/resources/templates/login.html
Labels: enhancement
